FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -o /myapp

FROM scratch

COPY --from=builder /myapp /myapp
COPY --from=builder /app/templates/index.html /templates/

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /etc/passwd /etc/passwd

USER nobody

EXPOSE 8080

CMD ["/myapp", "serve"]